/*
 * Copyright (C) 2026 Mitch Trachtenberg — GPL v3
 */
package com.mjtrac.counter.service;

import com.mjtrac.counter.model.ScanSession;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.io.File;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Real, end-to-end verification of a non-default (60%, not 50%) percentToWin
 * threshold — the "tax measure" scenario named directly in the feature
 * request ("60% (plus one) which may be required for tax measures among
 * other things"). Drives the actual production pipeline (CountingService ->
 * ScannerService -> VoteRecordService -> VoteTallyService) against a real
 * ballot PDF+YAML generated by builder-core's BallotGenerationService (via
 * builder/src/test/java's PercentThresholdBuilder), and real mark-detection
 * reading back 10 ballot images: 7 marked "Yes", 3 marked "No" (70% Yes).
 *
 * 70% clears the 60% threshold (and would also clear the default 50%), so
 * this proves the full pipeline correctly carries a non-default
 * percentToWin from Contest -> exported YAML -> scanned MarkingResult ->
 * persisted ContestRecord -> the results report's winner determination and
 * "Non-default win threshold" banner. The boundary case (exactly 60% must
 * NOT win, since the check is strict ">") is already covered purely at the
 * unit level by WinnerRulesTest — no need to duplicate that here with a
 * second slow full-pipeline scan.
 */
@SpringBootTest(classes = PercentThreshold60IntegrationTest.TestConfig.class,
                 webEnvironment = SpringBootTest.WebEnvironment.NONE)
class PercentThreshold60IntegrationTest {

    @SpringBootApplication(scanBasePackages = "com.mjtrac.counter")
    @EntityScan("com.mjtrac.counter.entity")
    @EnableJpaRepositories("com.mjtrac.counter.repository")
    static class TestConfig {
    }

    @TempDir
    static Path tempDir;

    @DynamicPropertySource
    static void overrideDataDirs(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", () -> "jdbc:sqlite:" + tempDir.resolve("test.db"));
        registry.add("data.dir", () -> tempDir.resolve("pbss_data").toString());
        registry.add("scanner.scribble-outline-dir", () -> tempDir.resolve("pbss_data/scribbles").toString());
    }

    @Autowired
    private CountingService countingService;

    @Autowired
    private ResultsQueryService resultsQuery;

    @Test
    void sixtyPercentThresholdScanProducesExpectedWinner() throws Exception {
        URL resource = getClass().getClassLoader()
            .getResource("test-images/percent_threshold_60/ballot_1_1_0_1_1_1.yaml");
        assertThat(resource).as("percent_threshold_60 fixtures on classpath").isNotNull();
        File imagesDir = new File(resource.getFile()).getParentFile();

        // 300 DPI matches how these fixtures were actually rasterized
        // (pdftoppm -r 300 against the real generated ballot PDF).
        countingService.startNewSession(
            imagesDir.getAbsolutePath(), imagesDir.getAbsolutePath(),
            128, 8.0, 300, false, "", 8.5);
        countingService.startScan("pct60-test");

        long deadline = System.currentTimeMillis() + 60_000;
        while (countingService.getSession().scanning && System.currentTimeMillis() < deadline) {
            Thread.sleep(200);
        }
        assertThat(countingService.getSession().scanning).as("scan finished within 60s").isFalse();

        ScanSession session = countingService.getSession();
        assertThat(session.scanError).isNull();
        assertThat(session.processed()).isEqualTo(10);
        assertThat(session.reviewRequired)
            .as("none of the 10 should need manual review")
            .isEmpty();

        countingService.finish("pct60-test");

        Map<String, ResultsQueryService.ContestConfig> configs = resultsQuery.contestConfigByTitle();
        ResultsQueryService.ContestConfig cfg = configs.get("Measure A — 60% Threshold Test");
        assertThat(cfg).as("contest config carried through to DB").isNotNull();
        assertThat(cfg.percentToWin)
            .as("non-default 60% threshold survived generation -> scan -> persistence")
            .isEqualTo(60.0);

        List<ResultsQueryService.VoteRow> rows = resultsQuery.votesByContest();
        long yesVotes = rows.stream()
            .filter(r -> "Yes".equals(r.getCandidate()))
            .mapToLong(ResultsQueryService.VoteRow::getVoted).sum();
        long noVotes = rows.stream()
            .filter(r -> "No".equals(r.getCandidate()))
            .mapToLong(ResultsQueryService.VoteRow::getVoted).sum();
        assertThat(yesVotes).as("7 of 10 ballots marked Yes").isEqualTo(7);
        assertThat(noVotes).as("3 of 10 ballots marked No").isEqualTo(3);

        WinnerRules.Ranked yesRank = WinnerRules.rank(
            Map.of("Yes", yesVotes, "No", noVotes), cfg.maxVotes, cfg.percentToWin)
            .stream().filter(r -> r.name().equals("Yes")).findFirst().orElseThrow();
        assertThat(yesRank.winner())
            .as("70%% Yes clears the 60%% threshold (and would also clear the default 50%%)")
            .isTrue();

        File resultsReport = new File(countingService.getReportOutputDir(), "results_report.html");
        assertThat(resultsReport).as("results_report.html written").exists();
        String html = Files.readString(resultsReport.toPath());
        assertThat(html)
            .as("non-default threshold banner shown for this contest")
            .contains("Non-default win threshold");
        assertThat(html)
            .as("Yes marked as the winner")
            .contains("Yes &#10003; WINNER");
        assertThat(html)
            .as("No not marked as the winner")
            .doesNotContain("No &#10003; WINNER");
    }
}
