/*
 * Copyright (C) 2026 Mitch Trachtenberg — GPL v3
 */
package com.mjtrac.counter.service;

import com.mjtrac.counter.model.ScanSession;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.io.File;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Real, end-to-end verification of the five-candidate IRV bulk-tie-
 * elimination scenario also covered algorithmically (no images, no scan —
 * just runIrv() directly) by RcvTabulationServiceTest.
 * testFiveCandidateBulkTieElimination() in bCounter/blCounter. This test
 * instead drives the actual production pipeline counter's own Swing
 * MainFrame uses (CountingService -> ScannerService -> VoteRecordService),
 * against a REAL ballot PDF+YAML generated by builder-core's
 * BallotGenerationService (via builder/src/test/java's
 * RcvFiveCandidateBuilder) and REAL mark-detection reading back 10
 * ballot images actually marked (not synthetic DB rows) with:
 *   3x Candidate 1 rank 1, Candidate 2 rank 2
 *   2x Candidate 2 rank 1, Candidate 1 rank 2
 *   2x Candidate 3 rank 1, Candidate 1 rank 2
 *   2x Candidate 4 rank 1, Candidate 1 rank 2
 *   1x Candidate 5 rank 1, Candidate 1 rank 2
 *
 * Expected IRV (majority = floor(10/2)+1 = 6):
 *   Round 1: 3/2/2/2/1 — Candidate 5 alone at the minimum eliminated.
 *   Round 2: Candidate 1=4, Candidates 2/3/4 tied at 2 — the whole tied
 *            bottom layer is eliminated together (RcvTabulationService's
 *            documented "parallel elimination for ties at the bottom"),
 *            not just one of them.
 *   Round 3: Only Candidate 1 remains active — wins with all 10 ballots.
 */
@SpringBootTest(classes = RcvFiveCandidateIntegrationTest.TestConfig.class,
                 webEnvironment = SpringBootTest.WebEnvironment.NONE)
class RcvFiveCandidateIntegrationTest {

    @SpringBootApplication(scanBasePackages = "com.mjtrac.counter")
    @EntityScan("com.mjtrac.counter.entity")
    @EnableJpaRepositories("com.mjtrac.counter.repository")
    static class TestConfig {
    }

    @TempDir
    static Path tempDir;

    @DynamicPropertySource
    static void overrideDataDirs(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", () -> "jdbc:sqlite:" + tempDir.resolve("test.db"));
        registry.add("data.dir", () -> tempDir.resolve("pbss_data").toString());
        registry.add("scanner.scribble-outline-dir", () -> tempDir.resolve("pbss_data/scribbles").toString());
    }

    @Autowired
    private CountingService countingService;

    @Autowired
    private RcvTabulationService rcvTabulationService;

    @Test
    void fiveCandidateRcvScanProducesExpectedThreeRoundResult() throws Exception {
        URL resource = getClass().getClassLoader()
            .getResource("test-images/rcv_five_candidate/ballot_1_1_0_1_1_1.yaml");
        assertThat(resource).as("rcv_five_candidate fixtures on classpath").isNotNull();
        File imagesDir = new File(resource.getFile()).getParentFile();

        // 300 DPI matches how these fixtures were actually rasterized
        // (pdftoppm -r 300 against the real generated ballot PDF) — see
        // CountingServiceIntegrationTest's own javadoc for why this must
        // match the real image resolution, not be assumed.
        countingService.startNewSession(
            imagesDir.getAbsolutePath(), imagesDir.getAbsolutePath(),
            128, 8.0, 300, false, "", 8.5);
        countingService.startScan("rcv-test");

        long deadline = System.currentTimeMillis() + 60_000;
        while (countingService.getSession().scanning && System.currentTimeMillis() < deadline) {
            Thread.sleep(200);
        }
        assertThat(countingService.getSession().scanning).as("scan finished within 60s").isFalse();

        ScanSession session = countingService.getSession();
        assertThat(session.scanError).isNull();
        assertThat(session.processed()).isEqualTo(10);
        assertThat(session.reviewRequired)
            .as("none of the 10 should need manual review")
            .isEmpty();

        countingService.finish("rcv-test");

        // processFinalTally() already ran rcvTabulationService.tabulateAndWrite()
        // once automatically at the end of the scan loop (CountingService's
        // runScanLoop -> voteTally.processFinalTally()), writing rcv_report.html
        // into the real configured report dir. tabulateAndWrite() is
        // @Transactional(readOnly = true) and reads straight from the DB, so
        // calling it again here is safe/idempotent — it's just how the test
        // gets the RcvResult list back, since finish() doesn't return one.
        String reportOutputDir = countingService.getReportOutputDir();
        List<RcvTabulationService.RcvResult> results = rcvTabulationService.tabulateAndWrite(reportOutputDir);

        assertThat(results).hasSize(1);
        RcvTabulationService.RcvResult result = results.get(0);
        assertThat(result.contest).isEqualTo("Five-Candidate RCV Test");
        assertThat(result.outcome).isEqualTo("winner");
        assertThat(result.winner).isEqualTo("Candidate 1");
        assertThat(result.totalBallots).isEqualTo(10);
        assertThat(result.rounds).as("expected exactly 3 rounds").hasSize(3);

        var r1 = result.rounds.get(0);
        assertThat(r1.counts).containsExactlyInAnyOrderEntriesOf(java.util.Map.of(
            "Candidate 1", 3, "Candidate 2", 2, "Candidate 3", 2,
            "Candidate 4", 2, "Candidate 5", 1));
        assertThat(r1.eliminated).containsExactly("Candidate 5");

        var r2 = result.rounds.get(1);
        assertThat(r2.counts).containsExactlyInAnyOrderEntriesOf(java.util.Map.of(
            "Candidate 1", 4, "Candidate 2", 2, "Candidate 3", 2, "Candidate 4", 2));
        assertThat(r2.eliminated)
            .as("all three tied-at-minimum candidates eliminated together, not just one")
            .containsExactlyInAnyOrder("Candidate 2", "Candidate 3", "Candidate 4");

        var r3 = result.rounds.get(2);
        assertThat(r3.counts).containsExactlyInAnyOrderEntriesOf(java.util.Map.of("Candidate 1", 10));
        assertThat(r3.winner).isEqualTo("Candidate 1");

        File rcvReport = new File(reportOutputDir, "rcv_report.html");
        assertThat(rcvReport).as("rcv_report.html written").exists();
        String html = Files.readString(rcvReport.toPath());
        assertThat(html).contains("Five-Candidate RCV Test");
        assertThat(html).contains("Candidate 1");
    }
}
